### ISSUE TITLE
Write output vehicles 

### ISSUE THREAD

**Issue by tschlenther** [matsim-vsp/opt-drt#3]
It would be very nice to have the resulting vehicle fleet as vehicles file in order to use it as input for following runs...
Should be doable by calling org.matsim.contrib.dvrp.fleet.FleetWriter at the end of the last simulation..

Will probably tackle that myself shortly...

Maybe that should be done by the drt config itself..
@michalmac WDYT?

**Comment by michalmac** [comment]
Good idea👍 I would suggest adding it at the DVRP level, so it works not only for DRT.

I think we can have it always switched on (without adding yet another option to the config), it's a small file anyway.

**Comment by tschlenther** [comment]
see https://github.com/matsim-org/matsim-libs/pull/1189
