### ISSUE TITLE
Dump out modified fleet

### ISSUE THREAD

**Issue by tschlenther** [matsim-vsp/opt-drt#6]
Nowadays, we are struggling with runs that abort frequently :/

One problem is that, if optDrt is enabled, we can not really resume a run from some intermediate iteration, as the fleet is modified but not dumped out. This means a run that aborted has to be run from the very beginng :(  
(it's now happened several times in iteration 74X/750 for me..)

I therefore would like to suggest that the fleet is dumped out after every modification. This typically is only every X iterations and probably only requires less than 5 lines of code within the central controler listener of this package.

**Comment by ikaddoura** [comment]
sure, makes totally sense! go ahead.
